name: Generate clash rules files

on:
  workflow_dispatch:
  schedule:
    - cron: "30 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set ENV variables
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install dos2unix

      - name: Generate ir domain list
        run: |
          echo -e "ir\nxn--mgba3a4f16a" > ir-temp.txt
          curl -sSL https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/domains.txt | grep -Ev ".+\.ir$" | cat - ir-temp.txt | sort -u > ir.txt
          rm -f ir-temp.txt

      - name: Generate ads and tracking domain list
        run: |
          curl -sSL https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianBlockerHosts.txt > ads-and-tracking-raw.txt
          curl -sSL https://small.oisd.nl/domainswild2 >> ads-and-tracking-raw.txt
          curl -sSL https://raw.githubusercontent.com/badmojr/1Hosts/master/Lite/wildcards.txt >> ads-and-tracking-raw.txt
          curl -sSL https://pgl.yoyo.org/adservers/serverlist.php?hostformat=nohtml >> ads-and-tracking-raw.txt
          curl -sSL https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Apple-AdBlock.txt >> ads-and-tracking-raw.txt
          curl -sSL https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Huawei-AdBlock.txt >> ads-and-tracking-raw.txt
          curl -sSL https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Samsung-AdBlock.txt >> ads-and-tracking-raw.txt
          curl -sSL https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Xiaomi-Extension.txt >> ads-and-tracking-raw.txt
          cat ads-and-tracking-raw.txt | sed -e 's/^\(\*\|\.\|\-\|0.0.0.0 \)*//g' -e '/!\|@\|#\|*\|_\|\[\|]\|\[\|\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}\|10.10.34/d' -e '/^\s*$/d' | awk '{$1=$1};1' | dos2unix | sort -u > ads-and-tracking-temp.txt
          curl -sSL https://raw.githubusercontent.com/hagezi/dns-blocklists/main/whitelist.txt > whitelist-raw.txt
          curl -sSL https://raw.githubusercontent.com/hagezi/dns-blocklists/main/whitelist-referral.txt >> whitelist-raw.txt
          curl -sSL https://local.oisd.nl/commonly_whitelisted.php >> whitelist-raw.txt
          curl -sSL https://raw.githubusercontent.com/notracking/hosts-blocklists-scripts/master/hostnames.whitelist.txt >> whitelist-raw.txt
          cat whitelist-raw.txt | sed -e 's/^\(\*\|\.\|\-\)*//g' -e '/!\|@\|#\|*\|_\|\[\|]/d' -e '/^\s*$/d' | awk '{$1=$1};1' | dos2unix | sort -u > whitelist-temp.txt
          comm -23 ads-and-tracking-temp.txt whitelist-temp.txt > ads-and-tracking.txt
          rm -f ads-and-tracking-raw.txt whitelist-raw.txt ads-and-tracking-temp.txt whitelist-temp.txt

      - name: Generate malware domain list
        run: |
          curl -sSL https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-hosts.txt | sed -e 's/^\(\*\|\.\|\-\|0.0.0.0 \)*//g' -e '/!\|@\|#\|*\|_\|\[\|]/d' -e '/^\s*$/d' | awk '{$1=$1};1' | dos2unix | sort -u > malware.txt

      - name: Generate phishing domain list
        run: |
          curl -sSL https://malware-filter.gitlab.io/malware-filter/phishing-filter-hosts.txt | sed -e 's/^\(\*\|\.\|\-\|0.0.0.0 \)*//g' -e '/!\|@\|#\|*\|_\|\[\|]/d' -e '/^\s*$/d' | awk '{$1=$1};1' | dos2unix | sort -u > phishing.txt

      - name : Generate clash text rules
        run: |
          mkdir -p release
          cat ir.txt | sed -e 's/^/+./' | sed '1s/^/# clash\n/' > release/ir.txt
          cat ads-and-tracking.txt | sed -e 's/^/+./' | sed '1s/^/# clash\n/' > release/ads-and-tracking.txt
          cat malware.txt | sed -e 's/^/+./' | sed '1s/^/# clash\n/' > release/malware.txt
          cat phishing.txt | sed -e 's/^/+./' | sed '1s/^/# clash\n/' > release/phishing.txt

      - name : Generate clash yaml rules
        run: |
          prefix="  - '+."
          suffix="'"
          cat ir.txt | awk -v prefix="$prefix" '{print prefix $0}' | awk -v suffix="$suffix" '{print $0 suffix}' | sed '1s/^/payload:\n/' > release/ir.yaml
          cat ads-and-tracking.txt | awk -v prefix="$prefix" '{print prefix $0}' | awk -v suffix="$suffix" '{print $0 suffix}' | sed '1s/^/payload:\n/' > release/ads-and-tracking.yaml
          cat malware.txt | awk -v prefix="$prefix" '{print prefix $0}' | awk -v suffix="$suffix" '{print $0 suffix}' | sed '1s/^/payload:\n/' > release/malware.yaml
          cat phishing.txt | awk -v prefix="$prefix" '{print prefix $0}' | awk -v suffix="$suffix" '{print $0 suffix}' | sed '1s/^/payload:\n/' > release/phishing.yaml

      - name: Release and upload assets
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
